#!/usr/bin/python3
# SPDX-FileCopyrightText: 2026 Ibuki Haga
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math

def throwdis(v0, throw_rad, h):
    """
    v0         : 初速度        (m/s)
    throw_rad  : 投げる角度    (rad)
    h          : 投げる高さ    (m)
    """

    t = 0.0
    g = 9.806   # 重力加速度
    dt = 0.001  # 時間刻み（1ms）

    while True:
        y = h + v0 * math.sin(throw_rad) * t - 0.5 * g * t * t

        if y < 0:
            x = v0 * math.cos(throw_rad) * t
            print(f"{x:.3f}")
            print(f"{t:.3f}")

            vx = v0 * math.cos(throw_rad)
            vy = v0 * math.sin(throw_rad) - g * t

            v = math.hypot(vx, vy)
            print(f"{v:.3f}")

            landing_rad = math.atan2(vy, vx)
            landing_deg = math.degrees(landing_rad)
            print(f"{landing_deg:.3f}")
            return

        if t >= 60:
            sys.exit(1)
        t += dt

# 標準入力
data = sys.stdin.read().split()
if len(data) != 3:
    sys.exit(1)

v0 = float(data[0])
throw_deg = float(data[1])
h = float(data[2])

if h < 0:
    sys.exit(1)

throw_rad = math.radians(throw_deg)
throwdis(v0, throw_rad, h)
