#!/usr/bin/python3
# SPDX-FileCopyrightText: 2026 Ibuki Haga
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math

def throwdis(v0, theta_rad, H):
    """
    v0         : 初速度        (m/s)
    theta_rad  : 投げる角度    (rad)
    H          : 投げる高さ    (m)
    ground_rad : 地面の傾き    (rad)  ※正なら上り坂、負なら下り坂
    """

    t = 0.0
    g = 9.806   # 重力加速度
    dt = 0.001  # 時間刻み（1ms）

    while True:
        y = H + v0 * math.sin(theta_rad) * t - 0.5 * g * t * t

        if y < 0:
            x = v0 * math.cos(theta_rad) * t
            print(f"{x:.3f}")
            print(f"{t:.3f}")

            vx = v0 * math.cos(theta_rad)
            vy = v0 * math.sin(theta_rad) - g * t

            v = math.sqrt(vx**2 + vy**2)
            print(f"{v:.3f}")

            angle_rad = math.atan2(vy, vx)
            angle_deg = math.degrees(angle_rad)
            print(f"{angle_deg:.3f}")
            return

        if t >= 60:
            sys.exit(1)
        t += dt

v0 = float(sys.argv[1])
theta_deg = float(sys.argv[2])
theta_rad = math.radians(theta_deg)
H = float(sys.argv[3])
if H < 0:
    sys.exit(1)

throwdis(v0, theta_rad, H)
